CFLAGS="`printf '%s\n' "$CFLAGS" | sed 's/-flto//g'`"
CPPFLAGS="`printf '%s\n' "$CPPFLAGS" | sed 's/-flto//g'`"
CXXFLAGS="`printf '%s\n' "$CXXFLAGS" | sed 's/-flto//g'`"
FCFFLAGS="`printf '%s\n' "$FCFFLAGS" | sed 's/-flto//g'`"
FFLAGS="`printf '%s\n' "$FFLAGS" | sed 's/-flto//g'`"

RUSTFLAGS="`echo "$FFLAGS" | sed 's/-Clinker-plugin-lto//g'`"

CFLAGS="`printf '%s\n' "$CFLAGS" | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
CPPFLAGS="`printf '%s\n' "$CPPFLAGS" | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
CXXFLAGS="`printf '%s\n' "$CXXFLAGS" | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
FCFFLAGS="`printf '%s\n' "$FCFFLAGS" | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
FFLAGS="`printf '%s\n' "$FFLAGS" | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"

