CFLAGS="`echo $CFLAGS | sed 's/-flto//g'`"
CPPFLAGS="`echo $CPPFLAGS | sed 's/-flto//g'`"
CXXFLAGS="`echo $CXXFLAGS | sed 's/-flto//g'`"
FCFFLAGS="`echo $FCFFLAGS | sed 's/-flto//g'`"
FFLAGS="`echo $FFLAGS | sed 's/-flto//g'`"

CFLAGS="`echo | sed s/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
CPPFLAGS="`echo $CPPFLAGS | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
CXXFLAGS="`echo $CXXFLAGS | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
FCFFLAGS="`echo $FCFFLAGS | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
FFLAGS="`echo $FFLAGS | sed 's/-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing//g'`"
