server:
    verbosity: 1
    port: 53
    interface: 127.0.0.1

    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    # only allow local host
    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: ::0/0 refuse
    access-control: ::1 allow

    harden-glue: yes
    hide-identity: yes
    hide-version: yes

    # sec for waiting for an unknown server to reply
    unknown-server-time-limit: 30

    # max TTL in cache (seconds)
    cache-max-ttl: 1800
    prefetch: yes

forward-zone:
    name: "."
    forward-addr: 192.168.100.200
########    forward-addr: 9.9.9.9
########    forward-addr: 149.112.112.112

