#!/bin/sh

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
    # shellcheck disable=2046
    export $(dbus-launch)
fi

exec dbus-launch \
    flatpak run \
    --env=USE_WAYLAND=1 \
    com.discordapp.Discord \
    --enable-features=UseOzonePlatform \
    "$@"

