#!/usr/bin/env bash

DIM=$(xrandr | grep \* |awk '{print $1}')
s_width="$(sed 's/x.*//' <<< "$DIM")"
s_height="$(sed 's/^[^x]*x//' <<< "$DIM")"

w=$(echo $s_width / 1.5 | bc)
h=$(echo $s_height / 16 | bc)
x=$(echo $(echo $s_width / 2 | bc) - $(echo $w / 2 | bc) | bc)
y=$(echo $(echo $s_height / 20 | bc) - $(echo $h / 2 | bc) | bc)

# w=$s_width
# h=50
# x=0
# y=0

vol() {
    sh ~/bin/BSDNixVolume.sh -get
}

tim() {
    # printf "%(%a %d %b  - %l:%M %p)T"
    echo 🌡️
    # printf "%b" "\\uf1eb asdf"
}

wrksp() {
   cat /tmp/dwm_info/current_ws
}

bat() {
    sh ~/bin/battery-check.sh
}

for((;;)) {
    # printf "    %s    \\n" "$(vol)%{c}$(tim)%{r}$(wrksp)   $(bat)"
    # echo "test lasdfsf 🌡️"
    cur=TEST
    printf "%b" "\\uf1eb ${cur/connect}"
    echo asdf
    sleep 0.5
} |\

# -f "DejaVu Sans Mono" \
lemonbar -db \
         -g "$w"x"$h"+$x+$y \
         -n "bar" \
         -B "#d0c8c6" \
         -F "#0000000"
         # -f "Droid Sans Mono" \

# -f "Unifont" \
#          -f "DejaVu Sans Mono" \
#          -f "Roboto Mono" \
#          -f "Symbola" \
