#!/bin/sh

xrdb -load ~/.Xresources
xmodmap ~/.Xmodmap
xset +fp /home/$USER/.fonts

# if we have private ssh key(s), start ssh-agent and add the key(s)
# id1=$HOME/.ssh/identity
# id2=$HOME/.ssh/id_dsa
# id3=$HOME/.ssh/id_rsa
# if [ -z "$SSH_AGENT_PID" ];
# then
# 	if [ -x /usr/bin/ssh-agent ] && [ -f $id1 -o -f $id2 -o -f $id3 -o -f $id4 -o -f $id5 ];
# 	then
# 		eval `ssh-agent -s`
# 		ssh-add < /dev/null
# 	fi
# fi
# if [ "$SSH_AGENT_PID" ]; then
# 	ssh-add -D < /dev/null
# 	eval `ssh-agent -s -k`
# fi

# activate scroll wheel button (thinkpad)
# xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1 &
# xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5 &
# xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2 &
# xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Timeout" 50 &
# xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Inertia" 3 &

# increase pointer speed
# xinput set-prop "/dev/wsmouse" "Device Accel Constant Deceleration" 0.4 &



# exec openbox-session > /home/mitch/log.txt

exec dwm

# while true; do
    # dwm >/dev/null 2>&1
# done
