#!/bin/sh

wall=/etc/X11/xenodm/openbsd_wall.jpg
if [ -f $wall ] ; then
    if test -x /usr/local/bin/feh ; then
        /usr/local/bin/feh --no-fehbg --bg-fill $wall &
    elif test -x /usr/local/bin/hsetroot ; then
        /usr/local/bin/hsetroot -fill $wall &
    fi
fi
