#!/bin/sh

# # enable hardware acceleration in asahi
# # note: this is _very_ buggy and should be removed as soon as we can
# if uname -a | grep asahi >/dev/null ; then
#     export MESA_GL_VERSION_OVERRIDE=3.3
#     export MESA_GLSL_VERSION_OVERRIDE=330
#     export MESA_GLES_VERSION_OVERRIDE=3.1
# fi

exec dbus-launch \
    flatpak run \
    com.valvesoftware.Steam \
    "$@"

# --enable-features=UseOzonePlatform \
# --ozone-platform=wayland \

