# /etc/wsconsctl.conf

# "natural scrolling"
# make sure mouse1 is the touchpad via wsconsctl
mouse.reverse_scrolling=1
mouse1.reverse_scrolling=1
mouse2.reverse_scrolling=1

# enable tap to click on laptop touchpads
mouse.tp.tapping=1

# repeat delay/rate (ms)
keyboard.repeat.del1=230
keyboard.repeat.deln=20

# mute any beeps
keyboard.bell.volume=0

display.screen_off=60000
display.msact=off

