@@ -49,7 +49,8 @@
 	@sed "s/VERSION/${VERSION}/g" < st.1 > ${DESTDIR}${MANPREFIX}/man1/st.1
 	@chmod 644 ${DESTDIR}${MANPREFIX}/man1/st.1
 	@echo Please see the README file regarding the terminfo entry of st.
-	@tic -s st.info
+	@sed 's/st\([^t].*\)/st-git\1/g' st.info > st-git.info
+	@tic -s st-git.info
 
 uninstall:
 	@echo removing executable file from ${DESTDIR}${PREFIX}/bin
