#!/bin/sh

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
    # shellcheck disable=2046
    export $(dbus-launch)
fi

exec flatpak run \
    --env=USE_WAYLAND=1 \
    xyz.armcord.ArmCord \
    --enable-features=UseOzonePlatform \
    --ozone-platform=wayland
